# Generated by Django 5.2 on 2025-05-04 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_chat', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupdetail',
            name='type',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('chat', 'Chat')], default='private', max_length=10),
        ),
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('chat', 'Chat')], max_length=10),
        ),
    ]
