# Generated by Django 5.2 on 2025-04-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_chat', '0003_calllogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupdetail',
            name='type',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='private', max_length=10),
        ),
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], max_length=10),
        ),
    ]
