# Generated by Django 5.2.1 on 2025-05-09 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_chat', '0003_alter_groupdetail_type_alter_message_type'),
        ('django_chat', '0004_alter_groupdetail_type_alter_message_type'),
    ]

    operations = [
    ]
