# Generated by Django 5.2 on 2025-04-13 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_rest_authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
