# Generated by Django 5.2 on 2025-04-13 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_rest_authentication', '0002_usermodel_height_usermodel_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='hidden_regions',
            field=models.JSONField(default=list),
        ),
    ]
