# Generated by Django 5.2 on 2025-04-26 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_rest_authentication', '0003_usermodel_hidden_regions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='zip_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
