# Generated by Django 5.2 on 2025-05-03 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_live_streaming', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fanrelation',
            name='fan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_streamers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fanrelation',
            name='streamer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_fans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='streamgift',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='streammessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='streamreaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='streamsession',
            name='streamer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_streams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='streamreaction',
            name='stream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='django_live_streaming.streamsession'),
        ),
        migrations.AddField(
            model_name='streammessage',
            name='stream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='django_live_streaming.streamsession'),
        ),
        migrations.AddField(
            model_name='streamgift',
            name='stream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifts', to='django_live_streaming.streamsession'),
        ),
        migrations.AddField(
            model_name='streamwatchsession',
            name='stream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_live_streaming.streamsession'),
        ),
        migrations.AddField(
            model_name='streamwatchsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='fanrelation',
            unique_together={('streamer', 'fan')},
        ),
        migrations.AlterUniqueTogether(
            name='streamreaction',
            unique_together={('stream', 'user')},
        ),
    ]
