# Generated by Django 5.2 on 2025-04-13 14:31

import django_live_streaming.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_live_streaming', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamsession',
            name='saved_video',
            field=models.FileField(blank=True, null=True, upload_to=django_live_streaming.utils.user_stream_recordings_path),
        ),
    ]
