# Generated by Django 5.2.1 on 2025-05-08 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_live_streaming', '0002_alter_streamsession_saved_video'),
        ('django_live_streaming', '0002_initial'),
    ]

    operations = [
    ]
